Repository facebookresearch/maskrcnn-benchmark, pull requests merged in 2019-09, with the labels that each got.

#881 Update segmentation_mask.py
  maskrcnn_benchmark/structures/segmentation_mask.py
Labels: CLA Signed, good first issue

#1029 gamma, alpha are supposed to be floats, delete lines with [0] subscripts #1013
  maskrcnn_benchmark/layers/sigmoid_focal_loss.py
Labels: CLA Signed

#1028 fix minor typos
  maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py
  maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
  maskrcnn_benchmark/modeling/rpn/loss.py
Labels: CLA Signed

#1078 install local pip with conda
  INSTALL.md
Labels: CLA Signed

#911 Update INSTALL.md
  INSTALL.md
Labels: CLA Signed

#903 Add uncompressed rle condition in Binarymask
  maskrcnn_benchmark/structures/segmentation_mask.py
Labels: CLA Signed

#863 Update predictor.py
  demo/predictor.py
Labels: CLA Signed, enhancement, good first issue

#1043 remove redundant reshape of box_regression
  maskrcnn_benchmark/modeling/rpn/retinanet/inference.py
Labels: CLA Signed

#740 Update lr scheduling to pytorch 1.1.0
  maskrcnn_benchmark/engine/trainer.py
Labels: CLA Signed

#828 Validation during training (version 2)
  configs/e2e_mask_rcnn_R_50_FPN_1x_periodically_testing.yaml
  maskrcnn_benchmark/config/defaults.py
  maskrcnn_benchmark/data/build.py
  maskrcnn_benchmark/engine/trainer.py
  tools/train_net.py
Labels: CLA Signed
