Repository facebookresearch/maskrcnn-benchmark, pull requests merged in 2019-10, with the labels that each got.

#1142 Redirect users to Detectron2
  README.md
Labels: CLA Signed

#1126 replacing dtype torch.uint8 with torch.bool for indexing in pytorch 1.2.0
  demo/predictor.py
  maskrcnn_benchmark/modeling/balanced_positive_negative_sampler.py
  maskrcnn_benchmark/modeling/roi_heads/keypoint_head/loss.py
  maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py
  maskrcnn_benchmark/modeling/rpn/anchor_generator.py
  maskrcnn_benchmark/modeling/rpn/inference.py
  maskrcnn_benchmark/structures/segmentation_mask.py
Labels: CLA Signed, good first issue

#1104 Add native CityScapes evaluation tool
  maskrcnn_benchmark/data/datasets/evaluation/__init__.py
  maskrcnn_benchmark/data/datasets/evaluation/cityscapes/__init__.py
  maskrcnn_benchmark/data/datasets/evaluation/cityscapes/cityscapes_eval.py
  maskrcnn_benchmark/data/datasets/evaluation/cityscapes/eval_instances.py
Labels: CLA Signed

#1096 Extend COCO evaluation for AbstractDataset
  maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py
  maskrcnn_benchmark/data/datasets/evaluation/coco/abs_to_coco.py
  maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval_wrapper.py
Labels: CLA Signed, enhancement

#1111 bugfix: use correct config for tta and device handling during inference
  maskrcnn_benchmark/engine/inference.py
  tools/test_net.py
  tools/train_net.py
Labels: CLA Signed

#1090 Add native CityScapes dataset
  INSTALL.md
  configs/cityscapes/e2e_mask_rcnn_R_50_FPN_1x_binarymask.yaml
  configs/cityscapes/e2e_mask_rcnn_R_50_FPN_1x_poly.yaml
  maskrcnn_benchmark/config/paths_catalog.py
  maskrcnn_benchmark/data/datasets/__init__.py
  maskrcnn_benchmark/data/datasets/cityscapes.py
Labels: CLA Signed

#1095 Move horizontal flip probability to config
  maskrcnn_benchmark/config/defaults.py
  maskrcnn_benchmark/data/transforms/build.py
Labels: CLA Signed, needs discussion
